name: Plugins - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v3

      - name: Checkout Client
        uses: actions/checkout@v3
        with:
          repository: runelite/runelite
          ref: master
          path: runelite

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: runelite

      - name: Building client
        run: ./gradlew build -x test -x checkstyleMain --console=plain
        working-directory: runelite

      - name: Upload client artifacts to local maven
        run: ./gradlew publishToMavenLocal --console=plain
        working-directory: runelite

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build