name: Plugins - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build

  bootstrap:
    runs-on: ubuntu-latest
    needs: [build]
    name: Bootstrap

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Checkout plugins
        uses: actions/checkout@v3

      - name: Checkout plugins
        uses: actions/checkout@v3
        with:
          repository: OreoCupcakes/kotori-ported-plugins-hosting
          ref: master
          persist-credentials: false
          fetch-depth: 0



      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build

      - name: Bootstrapping plugins
        run: ./gradlew bootstrapPlugins

      - name: Copy bootstrap
        run: cp -af /home/runner/work/kotori-ported-plugins/kotori-ported-plugins/bootstrap/. /home/runner/work/kotori-ported-plugins/kotori-ported-plugins-hosting/

      - name: Copy Info
        run: cp -af /home/runner/work/kotori-ported-plugins/kotori-ported-plugins/info.json /home/runner/work/kotori-ported-plugins/kotori-ported-plugins-hosting/

      - name: Copy Hooks
        run: cp -af /home/runner/work/kotori-ported-plugins/kotori-ported-plugins/hooks.json /home/runner/work/kotori-ported-plugins/kotori-ported-plugins-hosting/

      - name: Commit bootstrap
        run: |
          git add $(git ls-files -o --exclude-standard) *.json
          git diff-index --quiet HEAD \
          || git -c user.name="GitHub" -c user.email="noreply@github.com" commit \
            --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
            -m "Automatic plugin bootstrap"
        working-directory: /home/runner/work/kotori-ported-plugins/kotori-ported-plugins-hosting

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.OreoCupcakes }}
          directory: /home/runner/work/kotori-ported-plugins/kotori-ported-plugins-hosting
          repository: OreoCupcakes/kotori-ported-plugins-hosting
