name: Plugins - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Checkout Plugins
        uses: actions/checkout@v3

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/kotori-ported-plugins/plugins

      - name: Assembling plugins
        run: ./gradlew --console=plain
        working-directory: /home/runner/work/kotori-ported-plugins/plugins

      - name: Building plugins
        run: ./gradlew
        working-directory: /home/runner/work/kotori-ported-plugins/plugins

      - name: Upload plugins artifacts to local maven
        run: ./gradlew --console=plain
        working-directory: /home/runner/work/kotori-ported-plugins/plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build

  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bootstrap:
    runs-on: ubuntu-latest
    needs: [build]
    name: Bootstrap

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Checkout plugins
        uses: actions/checkout@v3

      - name: Checkout plugins
        uses: actions/checkout@v3
        with:
          repository: OreoCupcakes/kotori-ported-plugins
          ref: master

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/kotori-ported-plugins/plugins

      - name: Assembling plugins
        run: ./gradlew --console=plain
        working-directory: /home/runner/work/kotori-ported-plugins/plugins

      - name: Building plugins
        run: ./gradlew
        working-directory: /home/runner/work/kotori-ported-plugins/plugins

      - name: Upload plugins artifacts to local maven
        run: ./gradlew --console=plain
        working-directory: /home/runner/work/kotori-ported-plugins/plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build

      - name: Bootstrapping plugins
        run: ./gradlew bootstrapPlugins

      - name: Copy bootstrap
        run: cp -af /home/runner/work/kotori-ported-plugins/kotori-ported-plugins/build/bootstrap/. /home/runner/work/kotori-ported-plugins/plugins-release/

      - name: Commit bootstrap
        run: |
          git add $(git ls-files -o --exclude-standard) plugins.json info.json hooks.json
          git diff-index --quiet HEAD \
          || git -c user.name="GitHub" -c user.email="noreply@github.com" commit \
            --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
            -m "Automatic plugin bootstrap"
        working-directory: /home/runner/work/kotori-ported-plugins/plugins-release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.OreoCupcakes }}
          directory: /home/runner/work/kotori-ported-plugins/plugins-release
          repository: OreoCupcakes/kotori-ported-plugins-hosting
