name: Plugins - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build